server:
  port: 0

spring:
  application:
    name: demo-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: http://localhost:8080/realms/appsdeveloperblog
          jwk-set-uri: http://localhost:8080/realms/appsdeveloperblog/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
